LANGUAGE_MAP = {
    "hello": {"en": "hello", "hi": "namaste", "te": "namaste", "ta": "vanakkam"},
    "hi": {"en": "hi", "hi": "namaste", "te": "namaste", "ta": "vanakkam"},
    "thank_you": {"en": "thank you", "hi": "dhanyavaad", "te": "dhanyavadamulu", "ta": "nandri"},
    "yes": {"en": "yes", "hi": "haan", "te": "avunu", "ta": "aam"},
    "no": {"en": "no", "hi": "nahi", "te": "kaadu", "ta": "illai"},
    "please": {"en": "please", "hi": "kripya", "te": "dayachesi", "ta": "dayavu seidhu"},
    "what": {"en": "what", "hi": "kya", "te": "enti", "ta": "enna"},
    "eat": {"en": "eat", "hi": "khaana", "te": "tina", "ta": "sapidu"},
    "water": {"en": "water", "hi": "paani", "te": "neellu", "ta": "thanni"},
    "nice to meet you": {"en": "nice to meet you", "hi": "aap se milkar accha laga", "te": "mee to kalisi santoshamga undi", "ta": "ungalai sandhithathu magizhchiyai"},
    "sorry": {"en": "sorry", "hi": "maaf kijiye", "te": "kshaminchandi", "ta": "mannikkavum"},
    "good": {"en": "good", "hi": "achha", "te": "baagundi", "ta": "nallathu"},
    "help": {"en": "help", "hi": "madad", "te": "sahayam", "ta": "uthavi"},
    "stop": {"en": "stop", "hi": "ruk jao", "te": "nilabandi", "ta": "nillu"},
    "i don't know": {"en": "I don't know", "hi": "mujhe nahi pata", "te": "naku teliyadu", "ta": "enakku theriyathu"},
    "wait": {"en": "wait", "hi": "intezaar karo", "te": "naku veyandi", "ta": "kaathirunga"},
    "go": {"en": "go", "hi": "jao", "te": "vellandi", "ta": "po"},
    "call": {"en": "call", "hi": "call karo", "te": "call cheyandi", "ta": "call seyyunga"},
    "completed": {"en": "complete", "hi": "poora karo", "te": "poorthi cheyandi", "ta": "mudivu seidhu"},
    "done": {"en": "done", "hi": "ho gaya", "te": "aipoyindi", "ta": "mudichitu irukku"},
    "bad": {"en": "bad", "hi": "bura", "te": "chedu", "ta": "kallathu"},
    "name": {"en": "name", "hi": "naam", "te": "peru", "ta": "peyar"},
    "where": {"en": "where", "hi": "kahan", "te": "ekada", "ta": "engae"},
    "why": {"en": "why", "hi": "kyun", "te": "enduku", "ta": "yendru"},
    "peace": {"en": "peace", "hi": "shanti", "te": "shanti", "ta": "shanthiy"},
    "dislike": {"en": "dislike", "hi": "pasand nahi", "te": "ishtam ledu", "ta": "isaiyillai"},
    "need": {"en": "need", "hi": "zaroorat", "te": "avasyam", "ta": "aavashyam"},
    "work": {"en": "work", "hi": "kaam", "te": "panulu", "ta": "velai"},
    "Home": {"en": "home", "hi": "ghar", "te": "illu", "ta": "veedu"},
    "school": {"en": "school", "hi": "school", "te": "school", "ta": "school"},
    "friend": {"en": "friend", "hi": "dost", "te": "snehitudu", "ta": "thozhan"},
    "keep quite": {"en": "keep quiet", "hi": "chup raho", "te": "aadaagaa undandi", "ta": "saathiyama irunga"},
    "listen": {"en": "listen", "hi": "suno", "te": "vinandi", "ta": "kettukonga"},
    "super": {"en": "super", "hi": "shandar", "te": "ati uttamam", "ta": "athigam nalla"},
    "more": {"en": "more", "hi": "aur", "te": "inkem", "ta": "inimelum"},
    "my": {"en": "my", "hi": "mera", "te": "nanna", "ta": "en"},
    "is": {"en": "is", "hi": "hai", "te": "undi", "ta": "irukku"},
    "how": {"en": "how", "hi": "kaise", "te": "ela", "ta": "eppadi"},
    "you": {"en": "you", "hi": "aap", "te": "meeru", "ta": "neengal"},
    "your": {"en": "your", "hi": "aapka", "te": "meeku", "ta": "ungal"},
    "there": {"en": "there", "hi": "wahan", "te": "akkada", "ta": "angae"},
}
